build:
  image: default-bionic
  environment:
    php: 8.1
  nodes:
    analysis:
      dependencies:
        after:
          - composer require --dev "squizlabs/php_codesniffer=3.6.2"
    php8:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: false
checks:
  php: true
coding_style:
  php:
    spaces:
      general:
        linefeed_character: return-newline
      before_parentheses:
        closure_definition: true
      around_operators:
        concatenation: true
filter:
  dependency_paths:
    - "vendor/"
