build:
  image: default-bionic
  environment:
    php: 8.1
  nodes:
    php8:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
checks:
  php: true
coding_style:
  php:
    spaces:
      general:
        linefeed_character: return-newline
      before_parentheses:
        closure_definition: true
      around_operators:
        concatenation: true
filter:
  dependency_paths:
    - "vendor/"
